CREATE TABLE TEAM(
    ID INT DEFAULT NOT NULL AUTO_INCREMENT,
    TEAMNAME VARCHAR(255),
    REMARK VARCHAR(300)
)

CREATE TABLE ACTIVITY(
    ID INT DEFAULT NOT NULL AUTO_INCREMENT,
    ACTIVITYNAME VARCHAR(255),
    REMARK VARCHAR(300)
)

CREATE TABLE DOCTOR(
    ID INT DEFAULT NOT NULL AUTO_INCREMENT,
    NAME VARCHAR(255),
    DEGREE VARCHAR(255),
    TYPE VARCHAR(50),
    REMARK VARCHAR(300),
    STATUS BOOLEAN,
    TEAM_ID BIGINT
)
